root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  include_ext = ["go", "hbs", "js", "css"]
  include_dir = ["./views", "."]
  exclude_regex = ["_test.go"]
  exclude_dir = ["tmp"]
  delay = 500
  kill_delay = "0s"
  poll = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"