version: "3.7"

services:
  db:
    image: mariadb
    container_name: vftalk-db
    environment:
      MARIADB_DATABASE: "${MARIADB_NAME}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_TZ: "Asia/Makassar"
    command: "--default-time-zone=+08:00"
    ports:
      - "3306:3306"
    volumes:
      - ./_docker-data/mariadb:/var/lib/mysql
    networks:
      - vftalk-network
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-vftalk
    ports:
      - 8080:80
    links:
      - db:mysql
    environment:
      PMA_HOST: db
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      PMA_ARBITRARY: 1
    volumes:
      - /_docker-data/phpmyadmin
    networks:
      - vftalk-network
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog-vftalk
    ports:
      - 1025:1025
      - 8025:8025

networks:
  vftalk-network: